In [ ]:
import numpy as np

In [1]:
a = [1,2,3,4]
b = [5,6,7,8]
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

In [6]:
[a[i] + b[i] for i in range(len(a))]

[6, 8, 10, 12]

In [7]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [8]:
np.array([[1,2,3],[4,5,6]]).shape

(2, 3)

In [10]:
arr  = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr[0]

array([1, 2, 3])

In [12]:
arr[2:]

array([[7, 8, 9]])

In [13]:
arr[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr[1:,1:]    

array([[5, 6],
       [8, 9]])

In [17]:
arr[2:,2:]

array([[9]])

In [19]:
arr[:,:1]

array([[1],
       [4],
       [7]])

In [20]:
arr[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [21]:
arr[:,1:2]

array([[2],
       [5],
       [8]])

In [23]:
arr[0:1:2]

array([[1, 2, 3]])

In [25]:
arr[:,2]

array([3, 6, 9])

In [26]:
arr[:0]

array([], shape=(0, 3), dtype=int32)

In [27]:
arr[0:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [29]:
arr[:,2:]

array([[3],
       [6],
       [9]])

In [30]:
arr[0:,2:]

array([[3],
       [6],
       [9]])

In [31]:
arr[:,2:]

array([[3],
       [6],
       [9]])

In [32]:
arr[1:,2:]

array([[6],
       [9]])

In [36]:
arr[1:,::2]

array([[4, 6],
       [7, 9]])

In [37]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
np.eye(3,3).dtype

dtype('float64')

In [39]:
np.eye(3,3).astype(int).dtype

dtype('int32')

In [40]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [41]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [44]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(10,10,100)

array([], dtype=int32)

In [47]:
a[a>2]

array([3, 4])

In [49]:
a = np.arange(10)

In [50]:
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [53]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
#vector operation

In [54]:
a = np.array([1,2,3])
a**2

array([1, 4, 9])

In [55]:
np.array([6,8])
a+2

array([3, 4, 5])

In [ ]:
#vector addition with scalar values

In [58]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a+b

array([[ 6,  8],
       [10, 12]])

In [60]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [14]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [15]:
a.T

array([[1, 3],
       [2, 4]])

In [16]:
np.linalg.det(a)

-2.0000000000000004

In [17]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [18]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [19]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [22]:
a = np.array([1,2,3,4,5,6,7,8,9,10,4,1])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  1])

In [29]:
np.reshape(np.reshape(a,(3,4)),(6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 4,  1]])

In [27]:
np.resize(a,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  4,  1]])

In [30]:
np.reshape(np.reshape(a,(3,4)),(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  4,  1]])

In [31]:
np.reshape(np.reshape(a,(3,4)),(2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10,  4,  1]])

In [32]:
np.reshape(np.reshape(a,(3,4)),(4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  4,  1]])

In [33]:
a = np.array([1,2,3,4,5,6,7,8,10,4])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10,  4])

In [34]:
np.resize(a,(4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10,  4,  1,  2],
       [ 3,  4,  5,  6]])

In [35]:
a = np.array([1,2,3,4,5,6,7,8,9,10,4])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4])

In [38]:
np.resize(a,(4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  4,  1],
       [ 2,  3,  4,  5]])

In [40]:
a = np.array([1,2,3,4,5,6,7,8,10,4])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10,  4])

In [41]:
np.split(a,2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8, 10,  4])]

In [45]:
import numpy as np
np.random.seed(42)
scores = np.random.randint(50,101,size=(5,3))
mean_scores =  scores.mean(axis=0)
centered_scores = scores - mean_scores
print("Original Scores:\n",scores)
print("\nSubject-wise Mean:\n",mean_scores)
print("\nCentered Scores (After Mean Subtraction):\n",centered_scores)

Original Scores:
 [[88 78 64]
 [92 57 70]
 [88 68 72]
 [60 60 73]
 [85 89 73]]

Subject-wise Mean:
 [82.6 70.4 70.4]

Centered Scores (After Mean Subtraction):
 [[  5.4   7.6  -6.4]
 [  9.4 -13.4  -0.4]
 [  5.4  -2.4   1.6]
 [-22.6 -10.4   2.6]
 [  2.4  18.6   2.6]]


In [48]:
arr = np.array([1,2,3,4,5,6])
b = arr.view()
b[0] = 10
arr,b

(array([10,  2,  3,  4,  5,  6]), array([10,  2,  3,  4,  5,  6]))

In [52]:
c = arr.copy()
c[0] = 11
arr,c

(array([10,  2,  3,  4,  5,  6]), array([11,  2,  3,  4,  5,  6]))

In [53]:
import numpy as np
data = np.arange(24)
reshaped_data = data.reshape(4,3,2)
final_data = reshaped_data.transpose(0,2,1)
print("Final shape:", final_data.shape)
print(final_data)

Final shape: (4, 2, 3)
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]


In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.sum(a,axis=0)

array([12, 15, 18])

In [4]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [ ]:
import numpy as np
from scipy import stats

In [6]:
data = np.array([2,4,6,8])

In [7]:
mean = np.mean(data)
print(mean)

5.0


In [15]:
def mean(array):
    n = len(array)
    return np.sum(array)/n

In [16]:
mean(np.array([1,2,3,4,5,6]))

3.5

In [19]:
def variance(array):
    n = len(array)
    m = mean(array)
    return np.sum((array - m)**2)/n

In [20]:
variance(np.array([1,2,3,4,5,6]))

2.9166666666666665

In [36]:
import numpy as np
data = np.array([10,20,30,40,50])
min_val = data.min()
max_value = data.max()
scaled = (data - min_val) / (max_val - min_val)
print(scaled)

[0.   0.25 0.5  0.75 1.  ]


In [24]:
import numpy as np
data = np.array([10,20,30,40,50])
mean = data.mean()
std = data.std()
scaled = (data - mean) / std
print(scaled)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [32]:
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
x= np.array([-2,-1,0,1,2])
print(sigmoid(x))

[0.11920292 0.26894142 0.5        0.73105858 0.88079708]


In [35]:
import numpy as np
def relu(x):
    return np.maximum(0,x)
x = np.array([-3,-1,0,2,4])
print(relu(x))

[0 0 0 2 4]
